# Generated by Django 4.0 on 2022-04-07 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_userprofile_bio_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 4, 7, 3, 33, 7, 689383, tzinfo=utc), null=True),
        ),
    ]
