# Generated by Django 4.0 on 2022-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_queuenode_students_remove_userprofile_age_vipqueue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicqueue',
            name='head',
        ),
        migrations.RemoveField(
            model_name='queuenode',
            name='next',
        ),
        migrations.RemoveField(
            model_name='vipnode',
            name='next',
        ),
        migrations.RemoveField(
            model_name='vipqueue',
            name='head',
        ),
        migrations.AddField(
            model_name='basicqueue',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vipqueue',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
