# Generated by Django 4.0 on 2022-08-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_basicqueue_head_remove_queuenode_next_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuenode',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.userprofile'),
        ),
        migrations.AlterField(
            model_name='vipnode',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.userprofile'),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
