# Generated by Django 4.0 on 2022-09-02 09:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_queuenode_data_alter_vipnode_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheruser',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.TextField(default='student', verbose_name=django.contrib.auth.models.User),
        ),
        migrations.DeleteModel(
            name='BasicUser',
        ),
        migrations.DeleteModel(
            name='TeacherUser',
        ),
    ]
