# Generated by Django 4.0 on 2022-09-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_teacheruser_user_userprofile_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='type',
            new_name='roles',
        ),
    ]
