# Generated by Django 4.0 on 2022-09-09 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_decision_alter_vipqueue_data_delete_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
